bb_adapter:
  ./data/adapters.fa

bed_file:
  ./data/mm10_MGC_gene.bed

star_tool:
  /home/groups/CEDAR/tools/STAR/tags/2.5.3a/bin/Linux_x86_64/STAR

adapter-PE:
  ./data/TruSeq3-PE-2.fa

conf:
  /home/groups/CEDAR/tools/FastQ_Screen_Genomes/fastq_screen.conf

star_index:
  /home/groups/CEDAR/estabroj/indexes/Mus_musculus/UCSC/mm10/Sequence/Star2Index

project_id:
  project_id

base_dir:
  base_dir

omic_meta_data:
  #Path to metadata file
  /home/groups/CEDAR/estabroj/experiments/Braun-mouse-pipeline/data/LSD1metadata.txt

gtf_file:
  #Directory of gtf used to compile star index and annotate features
  /home/groups/CEDAR/estabroj/indexes/Mus_musculus/UCSC/mm10/Annotation/Archives/archive-2015-07-17-14-33-26/Genes/genes.gtf

seq_layout:
  # type of data paired-end | single-end : PE | SE
  PE

baseline:
  #Baseline for linear model - needs to be a factor in column listed for : linear_model 
  ND

linear_model:
  #Column name in meta data file to generate contrasts by
  Condition

sample_id:
  #Column name listing unique sample ids to be used. This needs to be the first column in the meta data file 
  SampleID

assembly:
  mm10

#fold change cutoff (not log2 transformed) for GO analysis
FC:
  2
#FDR adjusted p-value cutoff for GO analysis
adjp:
  0.01

meta_columns_to_plot:
  Condition: Condition

pca:
  labels:
    # columns of sample sheet to use for PCA and DE analysis
    - Condition

diffexp:
  # contrasts for the deseq2 results method - uses column indicated by pca[labels] above.  
  contrasts:
    #Name of contrast experiment
    GSK-vs-ND:
    #LSD1i:
      # factor level of treatment or contrast group
      - GSK
      # factor level of baseline of control group
      - ND

colors:
  rcolorbrewer:
    - NA
  discrete:
    - NA