bb_adapter:
  /home/exacloud/lustre1/CompBio/estabroj/data/snakemake/projects/beta4/data/adapters.fa

bed_file:
  /home/groups/CEDAR/estabroj/beta4/data/mm10_MGC_gene.bed

star_tool:
  /home/groups/CEDAR/tools/STAR/tags/2.5.3a/bin/Linux_x86_64/STAR

adapter-PE:
  /home/users/estabroj/scratch/data/snakemake/projects/beta4/data/TruSeq3-PE-2.fa

conf:
  /home/groups/CEDAR/tools/FastQ_Screen_Genomes/fastq_screen.conf

refflat2:
  /home/exacloud/lustre1/CEDAR/Genomes/gencode27_refflat2.txt

star_index:
  /home/groups/CEDAR/estabroj/indexes/Mus_musculus/UCSC/mm10/Sequence/Star2Index

project_id:
  name-of-project

base_dir:
  /path/to/base/project/directory/

omic_meta_data:
  #Path to metadata file
  /home/groups/CEDAR/estabroj/beta4/data/beta4_meta_data.txt

gtf_file:
  #Directory of gtf used to compile star index and annotate features
  /home/groups/CEDAR/estabroj/indexes/Mus_musculus/UCSC/mm10/Annotation/Archives/archive-2015-07-17-14-33-26/Genes/genes.gtf

seq_layout:
  # type of data paired-end | single-end : PE | SE
  PE

baseline:
  #Baseline for linear model - needs to be a factor in column listed for : linear_model 
  38-KC

linear_model:
  #Column name in meta data file to generate contrasts by
  Condition

sample_id:
  #Column name listing unique sample ids to be used. This needs to be the first column in the meta data file 
  SampleID

assembly:
  mm10

meta_columns_to_plot:
  Time: Time
  Condition: Condition
  Lane: Lane

pca:
  labels:
    # columns of sample sheet to use for PCA and DE analysis
    - Condition

diffexp:
  # contrasts for the deseq2 results method - uses column indicated by pca[labels] above.  
  contrasts:
    #Name of contrast experiment
    38-KC-B4-vs-38-wt:
      # factor level of treatment or contrast group
      - 38-KC-B4
      # factor level of baseline of control group
      - 38-wt
